# Digit Recognition

<em>Note: The next command will run digitrec.py, building and compiling a neural network, running the training dataset through it, and reading random selections from the test dataset in order to show the networks accuracy</em>

### Imports

First we need to import all the nessessary packages:

In [109]:
import keras as kr
import numpy as np
import sklearn.preprocessing as pre
import gzip

### Building the neural network

First we initialise the network using the sequential model, basically meaning we can add layers to the initialised network.

In [110]:
model = kr.models.Sequential()

Next we need to add the layers, in our case we want 784 input neurons (one for each pixel of our 24x24 image), 1000 neurons on a hidden inner layer, and another 400 neurons on a second hidden inner layer.

The number of neurons internal to the network is completely up to you, in fact, tweaking the number of layers and neurons can help improve the networks performance

In [111]:
model.add(kr.layers.Dense(units=1000, activation='linear', input_dim=784))
model.add(kr.layers.Dense(units=400, activation='relu'))

We also need to add 10 output neurons, one for each possible digit the image could be containing (0-9)

In [112]:
model.add(kr.layers.Dense(units=10, activation='softmax'))

Now lets compile the network, connecting all of the neurons to each of it's neighbouring layers neurons

In [113]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

As explained in my mnist dataset notebook, we must unzip the files containing the images, and corrisponding labels

In [124]:
with gzip.open('data/t10k-images-idx3-ubyte.gz', 'rb') as f:
    test_images = f.read()
    
with gzip.open('data/t10k-labels-idx1-ubyte.gz', 'rb') as f:
    test_labels = f.read()
    
with gzip.open('data/train-images-idx3-ubyte.gz', 'rb') as f:
    training_images = f.read()
    
with gzip.open('data/train-labels-idx1-ubyte.gz', 'rb') as f:
    training_labels = f.read()

Next we need to read the datasets into memory

In [125]:
training_images = ~np.array(list(training_images[16:])).reshape(60000, 28, 28).astype(np.uint8) / 255.0
training_labels =  np.array(list(training_labels[8:])).astype(np.uint8)

test_images = ~np.array(list(test_images[16:])).reshape(10000, 784).astype(np.uint8) / 255.0
test_labels = np.array(list(test_labels[8:])).astype(np.uint8)

We can view the images in an array by showing all white pixels as 0, and all other pixels as 1

In [116]:
image = ~np.array(list(test_images[16:])).reshape(10000, 28, 28).astype(np.uint8)

In [117]:
print((~image[0]).astype(np.bool).astype(np.uint8))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 

Now in order to put each pixel into a corrisponding neuron in the inputs of the network, we have to flatten the datasets into single arrays

In [118]:
neuron_inputs = training_images.reshape(60000, 784)

The labels need to be set up next, first we must encode the data, turning all the label dataset into binary values, and all in a 10x10 matrix

In [119]:
encoder = pre.LabelBinarizer()

In [120]:
encoder.fit(training_labels)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [121]:
neuron_outputs = encoder.transform(training_labels)

With both datasets set up, we are ready to start training the model

In [122]:
model.fit(neuron_inputs, neuron_outputs, epochs=20, batch_size=100)

Epoch 1/20
60000/60000 [==============================] - 16s 272us/step - loss: 0.7436 - acc: 0.7886
Epoch 2/20
60000/60000 [==============================] - 16s 267us/step - loss: 0.3929 - acc: 0.8874
Epoch 3/20
60000/60000 [==============================] - 16s 267us/step - loss: 0.3433 - acc: 0.8997
Epoch 4/20
60000/60000 [==============================] - 16s 267us/step - loss: 0.3128 - acc: 0.9097
Epoch 5/20
60000/60000 [==============================] - 18s 305us/step - loss: 0.2929 - acc: 0.9145
Epoch 6/20
60000/60000 [==============================] - 18s 302us/step - loss: 0.2734 - acc: 0.9207
Epoch 7/20
60000/60000 [==============================] - 18s 299us/step - loss: 0.2578 - acc: 0.9262
Epoch 8/20
60000/60000 [==============================] - 20s 328us/step - loss: 0.2431 - acc: 0.9300
Epoch 9/20
60000/60000 [==============================] - 20s 334us/step - loss: 0.2310 - acc: 0.9338
Epoch 10/20
60000/60000 [==============================] - 19s 310us/step - loss: 

So we now have a working neural network, let's try and test manually to see how well the network works

In [128]:
from random import randint
for i in range(20): #Run 20 tests
    print("=================================")
    randIndex = randint(0, 9999) #Get a random index to pull an image from
    test = model.predict(test_images[randIndex:randIndex+1]) #Pull the image from the dataset
    result = test.argmax(axis=1) #Set result to the highest array value
    print("The actual number: =>> ", test_labels[randIndex:randIndex+1])
    print("The network reads: =>> ", result)
    print("=================================")

The actual number: =>>  [6]
The network reads: =>>  [6]
The actual number: =>>  [4]
The network reads: =>>  [4]
The actual number: =>>  [9]
The network reads: =>>  [9]
The actual number: =>>  [3]
The network reads: =>>  [3]
The actual number: =>>  [1]
The network reads: =>>  [1]
The actual number: =>>  [2]
The network reads: =>>  [2]
The actual number: =>>  [7]
The network reads: =>>  [7]
The actual number: =>>  [2]
The network reads: =>>  [2]
The actual number: =>>  [8]
The network reads: =>>  [8]
The actual number: =>>  [3]
The network reads: =>>  [3]
The actual number: =>>  [8]
The network reads: =>>  [8]
The actual number: =>>  [0]
The network reads: =>>  [0]
The actual number: =>>  [8]
The network reads: =>>  [8]
The actual number: =>>  [8]
The network reads: =>>  [8]
The actual number: =>>  [4]
The network reads: =>>  [4]
The actual number: =>>  [2]
The network reads: =>>  [2]
The actual number: =>>  [6]
The network reads: =>>  [6]
The actual number: =>>  [9]
The network reads: =