# Digit Recognition

First we need to import all the nessessary packages:

In [86]:
import keras as kr
import numpy as np
import sklearn.preprocessing as pre
import gzip

### Building the neural network

First we initialise the network using the sequential model, basically meaning we can add layers to the initialised network.

In [87]:
model = kr.models.Sequential()

Next we need to add the layers, in our case we want 784 input neurons (one for each pixel of our 24x24 image), 1000 neurons on a hidden inner layer, and another 400 neurons on a second hidden inner layer.

The number of neurons internal to the network is completely up to you, in fact, tweaking the number of layers and neurons can help improve the networks performance

In [88]:
model.add(kr.layers.Dense(units=1000, activation='linear', input_dim=784))
model.add(kr.layers.Dense(units=400, activation='relu'))

We also need to add 10 output neurons, one for each possiable digit the image could be containing (0-9)

In [89]:
model.add(kr.layers.Dense(units=10, activation='softmax'))

Now lets compile the network, connecting all of the neurons to each of it's neighbouring layers neurons

In [90]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

As explained in my mnist dataset notebook, we must unzip the files containing the images, and corrisponding labels

In [99]:
with gzip.open('data/t10k-images-idx3-ubyte.gz', 'rb') as f:
    test_images = f.read()
    
with gzip.open('data/t10k-labels-idx1-ubyte.gz', 'rb') as f:
    test_labels = f.read()
    
with gzip.open('data/train-images-idx3-ubyte.gz', 'rb') as f:
    training_images = f.read()
    
with gzip.open('data/train-labels-idx1-ubyte.gz', 'rb') as f:
    training_labels = f.read()

Next we need to read the datasets into memory

In [100]:
training_images = ~np.array(list(training_images[16:])).reshape(60000, 28, 28).astype(np.uint8) / 255.0
training_labels =  np.array(list(training_labels[8:])).astype(np.uint8)

We can view the images in an array by showing all white pixels as 0, and all other pixels as 1

In [101]:
image = ~np.array(list(test_images[16:])).reshape(10000, 28, 28).astype(np.uint8)

In [102]:
print((~image[0]).astype(np.bool).astype(np.uint8))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 

Now in order to put each pixel into a corrisponding neuron in the inputs of the network, we have to flatten the datasets into single arrays

In [94]:
neuron_inputs = training_images.reshape(60000, 784)

The labels need to be set up next, first we must encode the data, turning all the label dataset into binary values, and all in a 10x10 matrix

In [95]:
encoder = pre.LabelBinarizer()

In [96]:
encoder.fit(training_labels)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [97]:
neuron_outputs = encoder.transform(training_labels)

With both datasets set up, we are ready to start training the model

In [98]:
model.fit(neuron_inputs, neuron_outputs, epochs=2, batch_size=100)

Epoch 1/2
60000/60000 [==============================] - 18s 298us/step - loss: 0.7546 - acc: 0.7868
Epoch 2/2
60000/60000 [==============================] - 17s 279us/step - loss: 0.3969 - acc: 0.8867


So we now have a working